global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

scrape_configs:
  # Kong Gateway metrics
  - job_name: 'kong-gateway'
    static_configs:
      - targets: ['kong:8001']
    scrape_interval: 15s
    metrics_path: /metrics
    scheme: http
    
  # Kong status metrics
  - job_name: 'kong-status'
    static_configs:
      - targets: ['kong:8001']
    scrape_interval: 30s
    metrics_path: /status
    scheme: http

  # Direct microservice metrics - Load balanced inventory-api instances
  - job_name: 'inventory-api-instance-1'
    static_configs:
      - targets: ['inventory-api-1:8001']
    scrape_interval: 15s
    metrics_path: /metrics
    scheme: http

  - job_name: 'inventory-api-instance-2'
    static_configs:
      - targets: ['inventory-api-2:8001']
    scrape_interval: 15s
    metrics_path: /metrics
    scheme: http

  - job_name: 'inventory-api-instance-3'
    static_configs:
      - targets: ['inventory-api-3:8001']
    scrape_interval: 15s
    metrics_path: /metrics
    scheme: http

  # Direct microservice metrics - Other services
  - job_name: 'retail-api-direct'
    static_configs:
      - targets: ['retail-api:8002']
    scrape_interval: 15s
    metrics_path: /metrics
    scheme: http

  - job_name: 'ecommerce-api-direct'
    static_configs:
      - targets: ['ecommerce-api:8000']
    scrape_interval: 15s
    metrics_path: /metrics
    scheme: http

  - job_name: 'reporting-api-direct'
    static_configs:
      - targets: ['reporting-api:8005']
    scrape_interval: 15s
    metrics_path: /metrics
    scheme: http

  # Saga Orchestrator API direct metrics
  - job_name: 'saga-orchestrator-api-direct'
    static_configs:
      - targets: ['saga-orchestrator-api:8004']
    scrape_interval: 15s
    metrics_path: /metrics
    scheme: http

  # Kong proxy metrics for microservices
  - job_name: 'kong-proxy-inventory'
    static_configs:
      - targets: ['kong:8000']
    scrape_interval: 15s
    metrics_path: /inventory/metrics
    scheme: http
    params:
      apikey: ['admin-api-key-12345']

  - job_name: 'kong-proxy-retail'
    static_configs:
      - targets: ['kong:8000']
    scrape_interval: 15s
    metrics_path: /retail/metrics
    scheme: http
    params:
      apikey: ['admin-api-key-12345']

  - job_name: 'kong-proxy-ecommerce'
    static_configs:
      - targets: ['kong:8000']
    scrape_interval: 15s
    metrics_path: /ecommerce/metrics
    scheme: http
    params:
      apikey: ['admin-api-key-12345']

  - job_name: 'kong-proxy-reporting'
    static_configs:
      - targets: ['kong:8000']
    scrape_interval: 15s
    metrics_path: /reporting/metrics
    scheme: http
    params:
      apikey: ['admin-api-key-12345']

  # Kong proxy saga-orchestrator metrics
  - job_name: 'kong-proxy-saga'
    static_configs:
      - targets: ['kong:8000']
    scrape_interval: 15s
    metrics_path: /saga/metrics
    scheme: http
    params:
      apikey: ['admin-api-key-12345']

  # Health checks via Kong
  - job_name: 'kong-health-checks'
    static_configs:
      - targets: ['kong:8000']
    scrape_interval: 30s
    metrics_path: /health
    scheme: http
    params:
      apikey: ['admin-api-key-12345']

  # Direct health checks for load balanced inventory-api instances
  - job_name: 'inventory-api-health-checks'
    static_configs:
      - targets: ['inventory-api-1:8001', 'inventory-api-2:8001', 'inventory-api-3:8001']
    scrape_interval: 30s
    metrics_path: /health
    scheme: http

  # Database metrics
  - job_name: 'inventory-db-loadbalanced'
    static_configs:
      - targets: ['inventory-db-lb:5432']
    scrape_interval: 30s
    metrics_path: /metrics
    scheme: http

  # Redis metrics
  - job_name: 'redis-loadbalanced'
    static_configs:
      - targets: ['redis-lb:6379']
    scrape_interval: 30s
    metrics_path: /metrics
    scheme: http

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 15s
    metrics_path: /metrics
    scheme: http 